name: Build PDF and Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare Fonts
        run: |
          mkdir -p fonts

          wget https://github.com/adobe-fonts/source-han-serif/releases/download/2.003R/09_SourceHanSerifSC.zip
          unzip -q 09_SourceHanSerifSC.zip
          find . -path "*/OTF/SimplifiedChinese/*.otf" -exec cp {} fonts/ \;

          wget https://github.com/alerque/libertinus/releases/download/v7.040/Libertinus-7.040.zip
          unzip -q Libertinus-7.040.zip
          cp Libertinus-7.040/static/OTF/*.otf fonts/

          ls -lh fonts/

      - name: Install Typst
        uses: typst-community/setup-typst@v3

      - name: Build PDF
        # build pdf with font-path
        run: typst c main.typ --input handout=true --font-path fonts/

      - name: Create Release and Upload PDF
        uses: softprops/action-gh-release@v1
        with:
          files: main.pdf
